# Import Libraries

In [19]:
# load libraries
import pandas as pd
import numpy as np
import os
import sys

sys.path.insert(0, os.path.abspath(".."))
from src.data_loader import load_dataset

In [20]:
# load dataset
# df = load_dataset("/Users/macbookpro/Desktop/customer_churn_dl/data/raw/customer_churn_data.csv")
df = load_dataset("../data/raw/customer_churn_data.csv")

In [21]:
# first 5 rows
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,Male,0,No,Yes,23,No,No phone service,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
1,CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,...,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
2,CUST0002,Male,1,No,No,51,Yes,No,DSL,No,...,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
3,CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
4,CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [22]:
# dataset shape
df.shape

(5880, 21)

In [23]:
# column names
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [24]:
# datatypes in dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5880 non-null   str
 1   gender            5880 non-null   str
 2   SeniorCitizen     5880 non-null   int64
 3   Partner           5880 non-null   str
 4   Dependents        5880 non-null   str
 5   tenure            5880 non-null   int64
 6   PhoneService      5880 non-null   str
 7   MultipleLines     5880 non-null   str
 8   InternetService   5880 non-null   str
 9   OnlineSecurity    5880 non-null   str
 10  OnlineBackup      5880 non-null   str
 11  DeviceProtection  5880 non-null   str
 12  TechSupport       5880 non-null   str
 13  StreamingTV       5880 non-null   str
 14  StreamingMovies   5880 non-null   str
 15  Contract          5880 non-null   str
 16  PaperlessBilling  5880 non-null   str
 17  PaymentMethod     5880 non-null   str
 18  MonthlyCharges    5880 non-null   float64
 19  TotalCharges      5880 non-null   float64
 20  Churn             5880 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.6 MB

In [25]:
# statistics of the dataset
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    5880.000000  5880.000000     5880.000000   5880.000000
mean        0.500680    36.549150       70.157779   2566.813165
std         0.500042    20.909674       28.804615   1910.017743
min         0.000000     1.000000       20.000000     20.030000
25%         0.000000    18.000000       45.717500   1020.217500
50%         1.000000    37.000000       70.155000   2136.445000
75%         1.000000    55.000000       95.457500   3767.665000
max         1.000000    72.000000      119.990000   8589.600000

In [26]:
# check for missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [27]:
# check for duplicate rows
df.duplicated().sum()

0

In [28]:
# check target variable
df['Churn'].value_counts()

Churn
No     2982
Yes    2898
Name: count, dtype: int64

In [29]:
# compute proportions
df['Churn'].value_counts(normalize=True)

Churn
No     0.507143
Yes    0.492857
Name: proportion, dtype: float64

In [30]:
# separate feature types
# numerical

numerical_features = df.select_dtypes(
    include=["int64", "float64"]
).columns

numerical_features

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')

In [31]:
# categorical
categorical_features = df.select_dtypes(
    include=["object"]
).columns

categorical_features

/var/folders/_k/br6984v13bd646948vbf7zvw0000gn/T/ipykernel_5741/2405187751.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')

In [32]:
# identify unique values
for col in categorical_features:
    print(col)
    print(df[col].unique())
    print("-" * 40)

customerID
<ArrowStringArray>
['CUST0000', 'CUST0001', 'CUST0002', 'CUST0003', 'CUST0004', 'CUST0005',
 'CUST0006', 'CUST0007', 'CUST0008', 'CUST0009',
 ...
 'CUST5870', 'CUST5871', 'CUST5872', 'CUST5873', 'CUST5874', 'CUST5875',
 'CUST5876', 'CUST5877', 'CUST5878', 'CUST5879']
Length: 5880, dtype: str
----------------------------------------
gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
----------------------------------------
Partner
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------
Dependents
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------
PhoneService
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------
MultipleLines
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------
InternetService
<ArrowStringArray>
['No', 'DSL', 'Fiber optic']
Length: 3, dtype: str
----------------------------------------
OnlineSecurity
<ArrowStringArray>
['No internet service', 'Yes', 'No']
Length: 3, dtype: str
----------------------------------------
OnlineBackup
<ArrowStringArray>
['No internet service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------
DeviceProtection
<ArrowStringArray>
['No internet service', 'Yes', 'No']
Length: 3, dtype: str
----------------------------------------
TechSupport
<ArrowStringArray>
['No internet service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------
StreamingTV
<ArrowStringArray>
['No internet service', 'Yes', 'No']
Length: 3, dtype: str
----------------------------------------
StreamingMovies
<ArrowStringArray>
['No internet service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------
Contract
<ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
----------------------------------------
PaperlessBilling
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------
PaymentMethod
<ArrowStringArray>
['Bank transfer', 'Mailed check', 'Electronic check', 'Credit card']
Length: 4, dtype: str
----------------------------------------
Churn
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------

In [33]:
# validate binary columns
binary_columns = [
    "SeniorCitizen", 
    "tenure", 
    "MonthlyCharges", 
    "TotalCharges"
]

for col in binary_columns:
    print(col, df[col].unique)

SeniorCitizen <bound method Series.unique of 0       0
1       0
2       1
3       1
4       1
       ..
5875    0
5876    0
5877    0
5878    0
5879    1
Name: SeniorCitizen, Length: 5880, dtype: int64>
tenure <bound method Series.unique of 0       23
1       43
2       51
3       72
4       25
        ..
5875    71
5876    22
5877    68
5878    14
5879    23
Name: tenure, Length: 5880, dtype: int64>
MonthlyCharges <bound method Series.unique of 0        49.85
1       100.70
2        97.33
3       101.38
4        52.22
         ...
5875     74.21
5876     65.43
5877     59.78
5878     91.88
5879     25.45
Name: MonthlyCharges, Length: 5880, dtype: float64>
TotalCharges <bound method Series.unique of 0       1146.55
1       4330.10
2       4963.83
3       7299.36
4       1305.50
         ...
5875    5268.91
5876    1439.46
5877    4065.04
5878    1286.32
5879     585.35
Name: TotalCharges, Length: 5880, dtype: float64>

In [34]:
# basic data quality report
report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
report

              Column Data Type  Missing Values  Unique Values
0         customerID       str               0           5880
1             gender       str               0              2
2      SeniorCitizen     int64               0              2
3            Partner       str               0              2
4         Dependents       str               0              2
5             tenure     int64               0             72
6       PhoneService       str               0              2
7      MultipleLines       str               0              3
8    InternetService       str               0              3
9     OnlineSecurity       str               0              3
10      OnlineBackup       str               0              3
11  DeviceProtection       str               0              3
12       TechSupport       str               0              3
13       StreamingTV       str               0              3
14   StreamingMovies       str               0              3
15          Contract       str               0              3
16  PaperlessBilling       str               0              2
17     PaymentMethod       str               0              4
18    MonthlyCharges   float64               0           4439
19      TotalCharges   float64               0           5794
20             Churn       str               0              2